sudo: required

services:
    - docker

install: 
  - docker-compose up -d

jobs:
  include:
    - stage: test
      script: docker-compose exec functions scripts/coverage.sh
    - if: branch = staging
      script: docker-compose exec functions zappa update staging || zappa deploy staging
    - if: branch = master
      script: docker-compose exec functions zappa update prod || zappa deploy prod
