sudo: required

services:
    - docker
env:
    - DOCKER_COMPOSE_VERSION=1.16.1

before_install:
    - printenv | grep ^TRAVIS_
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin

install: 
  - docker-compose up -d

jobs:
  include:
    - stage: test
      script: docker-compose exec sandbox scripts/coverage.sh
    - stage: e2e
      script: docker-compose exec functions scripts/e2e.sh
    - stage: deploy
      script: docker-compose exec functions scripts/deploy.sh
