language: python

python:
  - "2.7"

install: 
  - pip install pipenv zappa
  - pipenv install --dev 

jobs:
  include:
    - stage: test
      script: coverage run --source="$PWD/HittaSkyddsrum" --omit="*/tests/*" -m HittaSkyddsrum/tests/shelters && codecov
    - if: branch = staging
      script: zappa update staging || zappa deploy staging
    - if: branch = master
      script: zappa update prod || zappa deploy prod
